// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaStock.Models;

#nullable disable

namespace SistemaStock.Migrations
{
    [DbContext(typeof(SistemaStockContext))]
    [Migration("20260703152000_AddUsuarioIdToCategoriasYProductos")]
    partial class AddUsuarioIdToCategoriasYProductos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
